let start_btn = document.getElementById("start");
console.log(start_btn);
let budgetV = document.getElementsByClassName("budget-value");
console.log(budgetV);
let daybugetV = document.getElementsByClassName("daybudget-value");
console.log(daybugetV);
let levelV = document.getElementsByClassName('level-value');
console.log(levelV);
let expenV = document.getElementsByClassName('expenses-value');
console.log(expenV);
let optexpenV = document.getElementsByClassName('optionalexpenses-value');
console.log(optexpenV);
let incomeV = document.getElementsByClassName('income-value');
console.log(incomeV);
let monthsaveV = document.getElementsByClassName("monthsavings-value");
console.log(monthsaveV);
let yearsaveV = document.getElementsByClassName("yearsavings-value");
console.log(yearsaveV);
let expItem = document.getElementsByClassName('expenses-item');
console.log(expItem);
let button = document.getElementsByTagName("button");
let button1 = button[0], button2 = button[1], button3 = button[2];
let inputOptExpItem = document.querySelectorAll(".optionalexpenses-item");
console.log(inputOptExpItem);
let inpOptExp = document.querySelector(".optionalexpenses");
let checkboxSave = document.querySelector("#savings");
let sum = document.querySelector("#sum");
let percent = document.querySelector("#percent");
let year = document.querySelector(".year-value");
let month = document.querySelector(".month-value");
let day = document.querySelector(".day-value");